### ISSUE TITLE
w4-ETL-Project [Lucia_Costilla]

### ISSUE THREAD

**Issue by LuCostilla** [Ironhack-Data-Madrid-Agosto-2022/w4-ETL-Project#11]
https://github.com/LuCostilla/Project_W4_Oktoberfest.git

**Comment by Gobuub** [comment]
El proyecto tiene curro, el readme está bien explicado, pero falta un poco de orden el el repo, repartir los archivos en carpetas, cada una con su significado y tal, para que esté todo ordenadito ;).
