### ISSUE TITLE
w4-ETL-Project_[BertaNieto]

### ISSUE THREAD

**Issue by Vert-ix** [Ironhack-Data-Madrid-Agosto-2022/w4-ETL-Project#14]
https://github.com/Vert-ix/w4-ETL-Project_Berta.git

**Comment by Vert-ix** [comment]
Update:
https://github.com/Vert-ix/w4-ETL-Project_Berta.git

**Comment by Gobuub** [comment]
Buen trabajo, ya tienes datos para el proyecto de este finde si quieres :).
