### ISSUE TITLE
PERDONNN POR EL RETRASOO (el personal y el del plazo de entrega jej)

### ISSUE THREAD

**Issue by javiercanela3** [Ironhack-Data-Madrid-Agosto-2022/w4-ETL-Project#18]
https://github.com/javiercanela3/PROYECTO-4.git

**Comment by Gobuub** [comment]
A ver si sacamos un rato a ver porque solo te pilla la liga extra y no las demás ;), para que puedas tenerlas todas por si quieres continuar con el proyecto. Buen trabajo, pero la próxima semana entrégame el trabajo en tiempo :P.
