### ISSUE TITLE
w4-ETL-Project

### ISSUE THREAD

**Issue by AtomLu** [Ironhack-Data-Madrid-Agosto-2022/w4-ETL-Project#7]
https://github.com/AtomLu/ETL-project.git  [Lucia Correa]
PRESENTATION : https://docs.google.com/presentation/d/1ciRXUHsRgPGMlOKCPjaHmSrFe9ScghclKiHnsTi73_E/edit#slide=id.gd206afaa83_0_0

**Comment by Gobuub** [comment]
Buen trabajo Lucia, por poner un pequeño pero, echo de menos un poco de organización en el repo, distribuir los archivos en carpetas y que cada uno esté en su sitio y no todo en el principal, salvo eso, todo guay.
