### ISSUE TITLE
w4-ETL-Project [Alonso Herrera]

### ISSUE THREAD

**Issue by aherreraitie** [Ironhack-Data-Madrid-Agosto-2022/w4-ETL-Project#8]

**Comment by aherreraitie** [comment]
https://github.com/aherreraitie/w4-ETL-Project

**Comment by Gobuub** [comment]
El trabajo tiene mucho curro Alonso, y bueno para la gente que le gustan las efemérides puede ser curioso :). Buen trabajo.
