### ISSUE TITLE
w4-ETL-Project {Antonio López-Alanís}

### ISSUE THREAD

**Issue by antlopal3rd** [Ironhack-Data-Madrid-Agosto-2022/w4-ETL-Project#9]

**Comment by antlopal3rd** [comment]
https://github.com/antlopal3rd/wines_ETL.git

**Comment by antlopal3rd** [comment]
https://docs.google.com/presentation/d/1CoMrINsFbZXQumcoGj79fq-kaPk1meHT-xC4o6LTFA4/edit?usp=sharing

**Comment by Gobuub** [comment]
Buen trabajo Antonio, mucho curro detrás :).
